
{{- $cnfHdr := (dict "" "") -}}
{{- include "cnfTplHeader_2_9" (dict "cnfHdr" $cnfHdr "dot" . ) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: xgvela-sa
  namespace: {{ $cnfHdr.nfVariables.nfPrefix }}
