
{{- if .Values.global.xgvela.infra_deploy -}}
{{- $cnfHdr := (dict "" "") -}}
{{- include "cnfTplHeader_2_9" (dict "cnfHdr" $cnfHdr "dot" . ) -}}
apiVersion: v1
kind: Service
{{- include "cnfTplMetadata_2_9" (dict "setOffset" "0" "cnfHdr" $cnfHdr "metadata" .Values.componentSpec.service.metaspec) }}
spec:
  type: {{ .Values.service.svc_type }}
  ports:
  - port: {{ .Values.service.ports.client }} 
    name: client
  - port: {{ .Values.service.ports.server }} 
    name: server
  - port: {{ .Values.service.ports.http }} 
    name: http
  selector:
    app: {{ .Values.common.app_name }}
{{- end -}}
